name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get (nightly) TLC
      run: wget https://nightly.tlapl.us/dist/tla2tools.jar
    - name: Get (nightly) CommunityModules
      run: wget https://github.com/tlaplus/CommunityModules/releases/latest/download/CommunityModules-deps.jar
    - name: Run
      run: /bin/bash .github/workflows/run.sh
